config/routes.rb
Rails.application.routes.draw do
  resources :lists
  root 'lists#index'
  delete 'home/delete_completed'
  delete 'home/delete_all'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/list.rb
class List < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def delete_completed
    @delete_completed = List.where(:completed => true).destroy_all
    redirect_to lists_url, notice: "Completed tasks deleted."
  end

  def delete_all
    @delete_all = List.all.destroy_all
    redirect_to lists_url, notice: "All tasks deleted."
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[ show edit update destroy ]

  # GET /lists or /lists.json
  def index
    @list = List.new
    @lists = List.all

  end

  # GET /lists/1 or /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists or /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to lists_url, notice: "List was successfully created." }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1 or /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to lists_url, notice: "List was successfully updated." }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1 or /lists/1.json
  def destroy
    @list.destroy

    respond_to do |format|
      format.html { redirect_to lists_url, notice: "List was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:description, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-secondary" data-bs-theme="dark">
  <div class="container-fluid">
    <%= link_to 'To-do list', lists_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <div class="d-flex justify-content-center">
      <% if request.path == root_path || request.path == lists_path %>
        <%= render 'form2', list: @list%> 
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application" %>

  </head>

  <body>
    <%= render 'layouts/navbar' %>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    <div class="container">
      <%= render 'flash_messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_flash_messages.html.erb
<br>
<% if notice %>
	<div class="alert alert-success alert-dismissible fade show" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
        </button>
		<%= notice %>
	</div>
<% end %>

<% if alert %>
	<div class='alert alert-danger alert-dismissible fade show '>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
          
        </button>
		<%= alert %>
	</div>
<% end %>

app/views/lists/_form.html.erb
<%= form_with(model: list) do |form| %>
  <% if list.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="card" style="width: 20rem;">
  
  <div class="card-body">
    <div class="my-2">
      <%= form.label :description, style: "display: block" %>
      <%= form.text_field :description %>
    </div>

    <div class="form-group form-check my-4">
      <%= form.check_box :completed, class:"form-check-input"  %>
      <%= form.label :completed, style: "display: block", class: "form-check-label" %>
    </div>

    <div>
      <%= form.submit "Update", class:"btn btn-outline-success" %>
    </div>
  </div>
</div>

 
<% end %>

app/views/lists/_form2.html.erb
<%= form_with(model: list) do |form| %>
  <% if list.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group d-flex justify-content-between">
        <div>
            <%= form.text_field :description, placeholder:"new to-do", class:"form-control me-2" %>
        </div>
        <div class="d-flex ms-3">
            <%= form.submit "Add to-do", class:"btn btn-outline-success" %>
        </div>
    </div>
<% end %>

app/views/lists/_list.html.erb
<% if list.completed %>
  <tr class="table-secondary" id="<%= dom_id list %>">
    <td><%= link_to list.description, edit_list_path(list), class: "text-decoration-line-through text-dark" %></td>
    <td>
      <%= form_with(model: list) do |form| %>
        <%= form.text_field :description, type: 'hidden' %>
        <%= form.check_box :completed, :checked => false, :style => 'visibility: hidden'  %>
        <%= form.submit "Uncross", class:"btn btn-outline-dark  btn-sm" %>
      <% end %>
    </td>
    <td class="text-center">
      <%= link_to "Delete", list, data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class:"btn btn-outline-danger btn-sm text-dark" %>
    </td>
  </tr>
<% else %>
  <tr class="table" id="<%= dom_id list %>">
    <td><%=link_to list.description, edit_list_path(list), class: "text-decoration-none" %></td>
    <td>
      <%= form_with(model: list) do |form| %>
        <%= form.text_field :description, type: 'hidden' %>
        <%= form.check_box :completed, :checked => true, :style => 'visibility: hidden'  %>
        <%= form.submit "Complete", class:"btn btn-success btn-sm text-dark" %>
      <% end %>
    </td>
    <td class="text-center">
      <%= link_to "Delete", list, data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class:"btn btn-outline-danger btn-sm text-dark" %>
    </td>
  </tr>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing to-do item</h1>

<%= render "form", list: @list %>

<br>

<div>
  <%= link_to "Back to lists", lists_path %>
</div>

app/views/lists/index.html.erb
<table class="table table-bordered">
  <thead>
    <tr>
    </tr>
  </thead>
  <tbody id="lists">
    <% @lists.each do |list| %>
      <%= render list %>
    <% end %>
  </tbody>
</table>

  <%= link_to "Delete Completed", home_delete_completed_path, data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} , class: "text-decoration-uderline text-dark" %> |
  <%= link_to "Delete All tasks", home_delete_all_path, data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} , class: "text-decoration-uderline text-dark" %> 

app/views/lists/new.html.erb
<h1>New task</h1>

<%= render "form", list: @list %>

<br>

<div>
  <%= link_to "Back to lists", lists_path %>
</div>

app/views/lists/show.html.erb
<table class="table table-bordered">
  <tr>
    <th>Description</th>
    <th>Actions</th>
  </tr>
  <%= render @list %>
</table>

<table>
  <tr>
    
    <td><%= link_to "Back to Lists", lists_path %></td>
   
  </tr>
</table>